#pragma once
#include <glad/gl.h>
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <glm/glm.hpp>
#include <linmath.h>
#include "glm/gtx/string_cast.hpp"
#include "glm/gtc/constants.hpp"
